### ISSUE TITLE
missing ORDER BY in view

### ISSUE THREAD

**Issue by DickBaker** [yorek/practical-azure-sql-db-for-modern-developers#10]
code on p108 includes ORDER BY in window function column but omits it from parent SELECT
 however (by VIEW rules) this would also require a TOP 100 PERCENT phrase

**Comment by yorek** [comment]
The code looks good to me:

```sql
CREATE OR ALTER VIEW [Sales].[OrderLinesRuninngTotal]
AS
SELECT 
	[OrderID],
	[OrderLineID],
	[Description],
	[Quantity],	
	SUM(Quantity) OVER (
		PARTITION BY [OrderID] 
		ORDER BY [OrderLineID] ROWS BETWEEN 
			UNBOUNDED PRECEDING AND 
			CURRENT ROW
	) AS RunningTotal	
FROM 
	[Sales].[OrderLines];
GO
```
The `ORDER BY` is used in the context of the OVER clause, so there is no need to put it after the `FROM` clause, which would otherwise force the usage of a TOP 100 PERCENT as views cannot be ordered (as you will apply the ORDER clause when *using* the view, not in the view's body). Make sense?
